#!/bin/bash

POSITIONAL=()
ADD=false
DEL=false

if [[ $# -gt 2 ]]; then
	echo "Error: Too much args!"
	exit 1
fi

key="$1"
case $key in
	-a|--add)
	ADD=true
	IP="$2"
	;;
	-d|--del)
	DEL=true
	;;
	-h|--help)
	echo "Usage: netAlias {COMMAND} [IP]"
	echo "Commands:"
	echo "  add | -a    <IP>       Add alias network interface."
	echo "                         Note: <IP> should be checked nobody used."
	echo "  del | -d               Delete alias network interface."
	echo
	echo "Examples:"
	echo "  - add: netAlias -a 192.168.0.18"
	echo "  - del: netAlias -d"
	exit 1
	;;
	*)
	netAlias --help
	exit 1
	;;
esac


if [[ ${ADD} == true ]]; then
	sudo ifconfig enp3s0:0 ${IP}
	echo "`ifconfig enp3s0:0`"
fi

if [[ ${DEL} == true ]]; then
	sudo ifconfig enp3s0:0 down
	sudo ifconfig enp3s0 down
	sudo ifconfig enp3s0 up
	echo "`ifconfig`"
fi


